### PR TITLE
Typo!

### PR DESCRIPTION
**Pull request by amitmerchant1990**
Hey,

You meant "tree" not "trie", right?

Regards.

### CODE REVIEW

**Comment by appetizermonster** [comment]
Trie is one of data structures. I think its not a typo

**Comment by kbrsh** [comment]
It's not a typo, a [trie](https://en.wikipedia.org/wiki/Trie) is a data structure for storing and searching through text.

**Comment by amitmerchant1990** [comment]
Okay. I think you should mention this reference link in readme so that it would be easier to understand.

**Comment by kbrsh** [comment]
@amitmerchant1990 I have a [blog post](https://blog.kabir.ml/posts/inside-wade.html) and a [pdf](https://raw.githubusercontent.com/kbrsh/wade/master/Wade.pdf) linked in the README with explanations.

**Comment by amitmerchant1990** [comment]
Cool. Thanks!

**Pull request closed without merging**
